_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  # MIN_SIZE_TEST: 0
  # MIN_SIZE_TEST: 400
  MIN_SIZE_TEST: 800
  # MAX_SIZE_TEST: 608
  MAX_SIZE_TEST: 1333