MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_backbone"
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.2
    POSITIVE_FRACTION: 0.25
    # BATCH_SIZE_PER_IMAGE: 512
    BATCH_SIZE_PER_IMAGE: 64
    PROPOSAL_APPEND_GT: False
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  RPN:
    POST_NMS_TOPK_TRAIN: 500
DATASETS:
  TRAIN: ("pp_finetune_train_coco",)
  TEST: ("pp_finetune_val_coco",)
SOLVER:
  # IMS_PER_BATCH: 16
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.02
  STEPS: (80000, 90000)
  MAX_ITER: 100000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)